
import { Note, NoteColor, NoteType, User, FontStyle, Notification } from './types';

export const COUNTRY_CODES = [
  { code: '+1', flag: '🇺🇸' },
  { code: '+966', flag: '🇸🇦' },
  { code: '+971', flag: '🇦🇪' },
  { code: '+20', flag: '🇪🇬' },
  { code: '+44', flag: '🇬🇧' },
  { code: '+91', flag: '🇮🇳' },
];

// Reordered: For You first, Trending second
export const INTERESTS = [
  'For You', 'Trending', 'Poetry', 'Music', 'Quotes', 'Art', 'Daily Life', 'Comedy'
];

export const TRANSLATIONS = {
  en: {
    tagline: 'Share your echo',
    welcome: 'Welcome',
    enterPhone: 'Enter your number to continue to Notos.',
    phonePlaceholder: '000 0000',
    sending: 'Sending...',
    continue: 'Continue',
    enterCode: 'Enter the code sent to',
    demoCode: 'Demo Code:',
    verifying: 'Verifying...',
    verifyEnter: 'Verify & Enter',
    changeNumber: 'Change Number',
    newNote: 'New Note',
    post: 'Post',
    placeholder: "What's on your mind?",
    voiceNote: 'Voice Note',
    polishing: 'Polishing...',
    polish: 'Polish',
    autoTags: 'Auto Tags',
    home: 'Home',
    discover: 'Discover',
    activity: 'Activity',
    profile: 'Profile',
    searchPlaceholder: 'Search poets, tags...',
    trending: 'Trending #Tags',
    featured: 'Top Creators',
    follow: 'Follow',
    unfollow: 'Unfollow',
    following: 'Following',
    followers: 'Followers',
    liked: 'liked your note.',
    startedFollowing: 'started following you.',
    notes: 'Notes',
    likes: 'Likes',
    noNotes: 'No notes yet.',
    settings: 'Settings',
    editProfile: 'Edit Profile',
    coverUrl: 'Cover Image URL',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    username: 'Username',
    bio: 'Bio',
    comments: 'Comments',
    addComment: 'Add a comment...',
    logout: 'Logout',
    accounts: 'Accounts',
    tags: 'Tags',
    postsWith: 'Posts with',
    plain: 'Plain', sun: 'Sun', sky: 'Sky', rose: 'Rose', mystic: 'Mystic', midnight: 'Midnight'
  },
  ar: {
    tagline: 'Share your echo',
    welcome: 'مرحباً بك',
    enterPhone: 'أدخل رقم هاتفك للمتابعة في نوتوس',
    phonePlaceholder: '000 0000',
    sending: 'جاري الإرسال...',
    continue: 'متابعة',
    enterCode: 'أدخل الرمز المرسل إلى',
    demoCode: 'رمز تجريبي:',
    verifying: 'جاري التحقق...',
    verifyEnter: 'تحقق ودخول',
    changeNumber: 'تغيير الرقم',
    newNote: 'ملاحظة جديدة',
    post: 'نشر',
    placeholder: 'بماذا تفكر؟',
    voiceNote: 'ملاحظة صوتية',
    polishing: 'جاري التحسين...',
    polish: 'تحسين',
    autoTags: 'وسوم تلقائية',
    home: 'الرئيسية',
    discover: 'اكتشف',
    activity: 'النشاط',
    profile: 'الملف الشخصي',
    searchPlaceholder: 'ابحث عن شعراء، وسوم...',
    trending: 'وسوم شائعة',
    featured: 'مبدعون مميزون',
    follow: 'متابعة',
    unfollow: 'إلغاء المتابعة',
    following: 'متابَعون',
    followers: 'متابِعون',
    liked: 'أعجب بملاحظتك',
    startedFollowing: 'بدأ بمتابعتك',
    notes: 'ملاحظات',
    likes: 'إعجابات',
    noNotes: 'لا توجد ملاحظات بعد.',
    settings: 'الإعدادات',
    editProfile: 'تعديل الملف',
    coverUrl: 'رابط صورة الغلاف',
    save: 'حفظ',
    cancel: 'إلغاء',
    name: 'الاسم',
    username: 'اسم المستخدم',
    bio: 'النبذة',
    comments: 'تعليقات',
    addComment: 'أضف تعليقاً...',
    logout: 'تسجيل خروج',
    accounts: 'حسابات',
    tags: 'وسوم',
    postsWith: 'المنشورات في',
    plain: 'عادي', sun: 'شمس', sky: 'سماء', rose: 'ورد', mystic: 'غموض', midnight: 'ليل'
  }
};
